# Generated by Django 5.0.6 on 2024-09-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_goal_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='time_spend',
            field=models.DurationField(null=True),
        ),
    ]
