# Generated by Django 5.0.6 on 2024-09-18 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_alter_step_time_spend'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='hours_week',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
    ]
