# Generated by Django 5.0.6 on 2024-09-21 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0005_step_hours_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='time_spend',
            new_name='total_time_spend',
        ),
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='track.step')),
            ],
        ),
    ]
