# Generated by Django 5.0.6 on 2024-09-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0006_rename_time_spend_step_total_time_spend_timelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
